version: '3.8'

networks:
  internal_net:
    driver: bridge
    internal: true
  external_net:
    driver: bridge
    internal: false

services:
  postgres-synapse:
    image: postgres:15
    networks:
      - internal_net
    environment:
      POSTGRES_DB: ${POSTGRES_SYNAPSE_DB}
      POSTGRES_USER: ${POSTGRES_SYNAPSE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_SYNAPSE_PASSWORD}
    volumes:
      - postgres-synapse:/var/lib/postgresql/data
  
  postgres-sliding-sync:
    image: postgres:15
    networks:
      - internal_net
    environment:
      POSTGRES_DB: ${POSTGRES_SLIDING_SYNC_DB}
      POSTGRES_USER: ${POSTGRES_SLIDING_SYNC_USER}
      POSTGRES_PASSWORD: ${POSTGRES_SLIDING_SYNC_PASSWORD}
    volumes:
      - postgres-sliding-sync:/var/lib/postgresql/data

  synapse:
    image: matrixdotorg/synapse:latest
    networks:
      - internal_net
      - external_net
    environment:
      SYNAPSE_CONFIG_PATH: /data/config
    volumes:
      - /data/matrix/synapse/data:/data
      - /data/matrix/synapse/media:/media_store
    depends_on:
      - postgres-synapse
    labels:
      - "traefik.http.routers.synapse.rule=Host(`matrix.apps.attraktor.janjaap.de`)"
    #ports:
    #  - "8008:8008"

  sliding-sync:
    image: ghcr.io/matrix-org/sliding-sync:latest
    networks:
      - internal_net
      - external_net
    depends_on:
      - synapse
      - postgres-sliding-sync
    #ports:
    #  - "8009:8009"
    environment:
      SYNCV3_SERVER: ${SYNAPSE_FQDN}
      SYNCV3_DB: "host=postgres-sliding-sync sslmode=disable port=5432 dbname=${POSTGRES_SLIDING_SYNC_DB} user=${POSTGRES_SLIDING_SYNC_USER} password=${POSTGRES_SLIDING_SYNC_PASSWORD}"
      SYNCV3_SECRET: ${SLIDING_SYNC_SECRET}
      SYNCV3_BINDADDR: 127.0.0.1:8009

  nginx:
    image: nginx:latest
    networks:
      - external_net
    volumes:
      - /data/matrix/nginx:/usr/share/nginx/html
    #ports:
    #  - "8888:80"

  # pgadmin:
  #   image: dpage/pgadmin4
  #   networks:
  #     - internal_net
  #     - external_net
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #   ports:
  #     - "5050:80"
  #   volumes:
  #     - ./pgadmin_data:/var/lib/pgadmin

  # backup:
  #   image: rclone/rclone:latest
  #   networks:
  #     - internal_net
  #   volumes:
  #     - ./backup_data:/backup
  #     - ./pg_data:/pg_data:ro
  #     - ./synapse_data:/synapse_data:ro
  #     - ./rclone:/config/rclone
  #   environment:
  #     AWS_ACCESS_KEY_ID: your_aws_access_key_id
  #     AWS_SECRET_ACCESS_KEY: your_aws_secret_access_key
  #   entrypoint: /bin/sh -c
  #   command: >
  #     apk add --no-cache bash coreutils && \
  #     echo '0 2 * * * /backup/backup.sh' | crontab - && \
  #     crond -f