server_name: matrix.cloud.attraktor.org

listeners:
  - port: 8008
    type: http
    resources:
      - names: [client, federation]

report_stats: False

logging:
  - module: synapse.storage.SQL
    level: INFO

use_x_forwarded: true
bind_addresses: ['127.0.0.1']
