http:
  listeners:
  - name: web
    resources:
    - name: discovery
    - name: human
    - name: oauth
    - name: compat
    - name: graphql
    - name: assets
    binds:
    - address: '[::]:8080'
    proxy_protocol: false
  - name: internal
    resources:
    - name: health
    binds:
    - host: localhost
      port: 8081
    proxy_protocol: false
  trusted_proxies:
  - 192.168.0.0/16
  - 172.16.0.0/12
  - 10.0.0.0/10
  - 127.0.0.1/8
  - fd00::/8
  - ::1/128
  public_base: http://[::]:8080/
  issuer: http://[::]:8080/
database:
  uri: postgresql://
  max_connections: 10
  min_connections: 0
  connect_timeout: 30
  idle_timeout: 600
  max_lifetime: 1800
email:
  from: '"Authentication Service" <root@localhost>'
  reply_to: '"Authentication Service" <root@localhost>'
  transport: blackhole
secrets:
  encryption: 3e2c23b481c4c6af89910f96edc81f5e9a82d3cee9b26d53eea04dc6fb2f59cd
  keys:
  - kid: AwnpGbBYp6
    key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEogIBAAKCAQEA3HcliWkoCMH+kiDLV7R16UAV007TlvpuOBc0jrugQCte3efL
      l03lqG7mRsxYoW99nWfp3r14VppKfzy2rjwRulNTCqwKv4nDDoBSYWhwfpkFaUpo
      mFEq+LusJoAdFO+r3fSm7Utw83ePt3+wai242AhbUaH6y+eUUYAE1AFa3GapP1hR
      zctMjHtRzxnGHsXW9T4aw4DdGxlhac7J0v9sRBKudMPT87Yrh3RYUvCvvdTMUyKh
      DmiwubKMG3WyPMsamLx4RbJ17BcRDqxWqJBoeh2QtuJ78K99MexzGFKAuxS2GSjF
      B0XVCk8ChmXpeqrC9GhStOJzi/D5r5LPwVn/kwIDAQABAoIBADFpAqCpUK+lysg1
      UV12tHZyRnH1WLadqdYoXT8gDepTzg8txBNFAhOdxz5WzgZgVmbQwzmIfU/rhIa/
      tLGYBOEdi574r+/9kBnP6KasIYo+AVh3tLlud5MHfK2kSOBIVtyH2GGWZtoqEauu
      kns5hBPmy5CgHPVWEYeyiWJ6a0K51PYDkLct7kWh91ydNMIZBOxvMAxQKtX6x9Tp
      h35qavKcNfWLFs61f5UXLxg+ipY56WpXY9onh+Q0l1BhBYDyzugMYWqEtp20bh8z
      lRgFLsuCVeWLa+DK13LYRuwcvd7I2/ce5Cr4ry8vQMrN9SfhCgalMn7VsKziQcti
      WbMnlAECgYEA6vc5TnGeq+5jheY6hBsI5tF5JQ1jhM/P1ZLw2I55J6bLtb2cvOmi
      QvQB3EOjXk9HzhS8Hr5vl+3/noCDGoKetZhhnSqIHlgNVFZxhuToTpAMDWf+tiQ/
      cncTljVYiE8lFFzWRUZWpWEtYjvb4Q++soKt92VugArcTmbcGzBD0vECgYEA8DOd
      gGJVPzsXSopBrI3Q5OPWT5XDJW7iZ1AmgrKkx7vT7c8d83PVMXRgAaWnEF9p3LSg
      RBkd3yT/anN7afVtX4OBLLGllOMLNEpTjk6h2O0dwjHdVXsrk2pCYhvNLXv+OXCP
      X8p4fZs3GWxNzFwIwRyv4Rim/g5qTeeYf8PRcsMCgYBmHkpuuFzQtovUjwoRjjph
      Ltsq6lW9TCA032cDh3BKdmiEtULgq93UoX4Jf/AJtgUsIMDdz8BqVIrLFWllZS2b
      GP4bs3dzUKuCYwt2KBh6xIoobXE7MifNFMmTd93haBxibDLH6tkPiVuTHRbkCtbD
      eJ4pLpFG3vF+tZ+lxWVE0QKBgHBrp+6bl0xlyqvfc4dgRIGsRPSwokoV0K8L60pG
      dCrrNPBbfKgh8YkY74o1zrAyB+j9PPlCTCHRPh3DeOKJtKv8b2vMpTO+49KQavTy
      xnsx1zi5f97vK+Dt3a3vVyNPoheeH+x0Zdpb1/j1IKBh/tLrK0IN+LJ1armViGFb
      895jAoGAXOTh/sIpjbgsix9n0tXYxw9iMWqGn9nhI5IeXEYOSfUDYCJCNsRxjk/Y
      DxZyjV+x36yO0ZKfxULsMKfv8LwjJlvpJUK4iWZIykhs0489/U3uFUQxYeLcWLjo
      MzdGsYztSumNeWDGUsFiWfrpopr6TupHsxUjRUc8GYzh0iG1oB8=
      -----END RSA PRIVATE KEY-----
  - kid: cYhJiOfHku
    key: |
      -----BEGIN EC PRIVATE KEY-----
      MHcCAQEEIGqRKoCK626znjZQrzNn97X5pF4qEEPl4eH24TrjZQcvoAoGCCqGSM49
      AwEHoUQDQgAELQnRQTgjeonIGxrOoywhE+7I/M4jk7CArEE7Zy3CffICce0IezKo
      tcbdb22pltS+0KSclfcZ7dpEGb3AoNo2sg==
      -----END EC PRIVATE KEY-----
  - kid: cGc2miQfdI
    key: |
      -----BEGIN EC PRIVATE KEY-----
      MIGkAgEBBDCgjp7em7sLQjgGC+VeK1a7/SyKHDXkafII+4ZNdMID1I5jolME1wkP
      lhzOzh0PbwGgBwYFK4EEACKhZANiAASarwPxSx88yHRn8//C2+3AIHZgT252ifLp
      vdt4BqEINQJr4yE4U/nM0l6ZMcJNpQJV1mluMcLNGNC0le9/j6nbBpYnCchYyAiA
      4G7rZxjTN0ULCw6yrcoNcfG6D953mKQ=
      -----END EC PRIVATE KEY-----
  - kid: VAhxYklHSK
    key: |
      -----BEGIN EC PRIVATE KEY-----
      MHQCAQEEIEiVKitWxukK3HyC3LSlkK0r2zp0i5l8erdE7LnfKLY9oAcGBSuBBAAK
      oUQDQgAEx/2qVDbXI10kvXQNdnHg7+JqC+EVOXFPWCX4INflKLMUkBlzO6O7LGfR
      U19d6ltWA686SOvX0l/suqTW4Nz9ZA==
      -----END EC PRIVATE KEY-----
passwords:
  enabled: true
  schemes:
  - version: 1
    algorithm: argon2id
  minimum_complexity: 3
matrix:
  homeserver: localhost:8008
  secret: nj9sWWOYLhVmsClICZzwHXZlhEA3ZYBZ
  endpoint: http://localhost:8008/