server_name: janjaap.de

listeners:
  - port: 8008
    type: http
    x_forwarded: true
    resources:
      - names: [client, federation]

report_stats: False

logging:
  - module: synapse.storage.SQL
    level: INFO

use_x_forwarded: true
bind_addresses: ['127.0.0.1']

trusted_key_servers:
  - server_name: "matrix.org"
suppress_key_server_warning: true

enable_registration: false
password_config:
  enabled: false

admin_contact: 'mailto:it@attraktor.org'